-- Adicionar colunas de endereço à tabela 'users'
ALTER TABLE users ADD COLUMN IF NOT EXISTS cep VARCHAR(9);
ALTER TABLE users ADD COLUMN IF NOT EXISTS logradouro VARCHAR(200);
ALTER TABLE users ADD COLUMN IF NOT EXISTS numero VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS complemento VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS bairro VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS cidade VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS estado VARCHAR(2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS retirar_na_loja BOOLEAN DEFAULT FALSE;
